In [2]:
import pandas as pd
import numpy as np
#import pickle
from sklearn.model_selection import train_test_split

In [3]:
path_2_train_file = '/Users/ganby/文件/ESCP/ML and Python/Assignment 2 and 3/train1.csv'
df = pd.read_csv(path_2_train_file)

In [4]:
df.columns

Index(['label', 'id', 'visitTime', 'purchaseTime', 'hour', 'C1', 'C2', 'C3',
       'C4', 'C5', 'C6', 'C7', 'C8', 'N1', 'C9', 'N2', 'N3', 'N4', 'N5', 'N6',
       'N7', 'N8', 'N9', 'N10', 'C10', 'C11', 'C12'],
      dtype='object')

In [5]:
df['C1'].value_counts()

2569487005    8430
2108523568       7
2084406919       6
3438432991       5
256353298        5
              ... 
1427705163       1
4180196685       1
596547023        1
3559230936       1
77004800         1
Name: C1, Length: 22595, dtype: int64

In [6]:
df['C3'].value_counts()

1928325921    1232
3475347077    1212
2780744710    1179
1711803242     936
1822656032     536
              ... 
3540895230       1
2756181513       1
3550862535       1
1199484467       1
1533319149       1
Name: C3, Length: 2863, dtype: int64

In [7]:
df['C10'].value_counts()

3469607743    1425
3458698981      82
3183725626      73
1133005353      71
3662869197      68
              ... 
843115400        1
762569609        1
4142922634       1
830608273        1
487200771        1
Name: C10, Length: 28653, dtype: int64

In [8]:
label = df['label'].values
label

array([-1, -1, -1, ..., -1, -1, -1])

In [9]:
data = df.drop(columns=['label','id','visitTime','purchaseTime','C1','C3','C10']).values
data

array([[         0, 1830830742,  652481754, ...,          0, 3617851689,
        4220791646],
       [         0,  403381353,  652481754, ...,          0, 3831440054,
        1213938795],
       [         0,  403381353,  652481754, ...,          0, 2379633508,
        1284343215],
       ...,
       [        23, 1235983246,  652481754, ...,          0,  621902171,
        3706004275],
       [        23,  403381353,  652481754, ...,          0, 3617851689,
        4220791646],
       [        23,  403381353,  652481754, ...,          0, 3617851689,
        4220791646]])

In [10]:
#测试drop掉这几列之后的df。
df000=df.drop(columns=['label','id','visitTime','purchaseTime','C1','C3','C10'])
df000

hour          C2          C4          C5          C6          C7  \
0         0  1830830742   652481754  2967512603  3624739744  2303407174   
1         0   403381353   652481754  2967512603   179712055  2303407174   
2         0   403381353   652481754  2967512603  1607619193  2303407174   
3         0   403381353   652481754  2967512603    10212495  2303407174   
4         0   403381353   652481754  2967512603   580883881  2303407174   
...     ...         ...         ...         ...         ...         ...   
31423    23  2018710401  2308170622  2967512603  3624739744  2303407174   
31424    23   403381353   652481754  2967512603  3624739744  2303407174   
31425    23  1235983246   652481754  2116767313  2304197778  2303407174   
31426    23   403381353   652481754  2967512603  3624739744  2303407174   
31427    23   403381353   652481754  2967512603  3624739744  2303407174   

               C8  N1          C9  N2  N3  N4  N5  N6  N7  N8  N9  N10  \
0      2206061889   0  4287642944   0   0   0   0   0   0   0   0    0   
1       157533148   1  3272771221   0   1   0   0   0   0   1   0    0   
2      3588031319   0  3329757940   0   0   0   0   0   0   0   0    0   
3      3588031319   0  3427046189   0   0   0   0   0   0   0   0    0   
4       157533148   0  2088887026   0   0   0   0   0   0   0   0    0   
...           ...  ..         ...  ..  ..  ..  ..  ..  ..  ..  ..  ...   
31423   157533148   0  4287642944   0   0   0   0   0   0   0   0    0   
31424   157533148   0  4287642944   0   0   0   0   0   0   0   0    0   
31425  2374954832   0  3179660634   0   0   0   0   0   0   0   0    0   
31426   434828410   0  4287642944   0   0   0   0   0   0   0   0    0   
31427   157533148   0  4287642944   0   0   0   0   0   0   0   0    0   

              C11         C12  
0      3617851689  4220791646  
1      3831440054  1213938795  
2      2379633508  1284343215  
3      3617851689  4220791646  
4      3617851689  4220791646  
...           ...         ...  
31423  3617851689  4220791646  
31424  3617851689  4220791646  
31425   621902171  3706004275  
31426  3617851689  4220791646  
31427  3617851689  4220791646  

[31428 rows x 20 columns]

In [11]:
X = data.copy()
y = np.array(label.copy())#把衡量购买的index复制一份。
y[:5]

array([-1, -1, -1, -1, -1])

In [12]:
y0 = (y > 0)*1
y0
#for i in y0:
#    if i>0:
#        print(i)
set(y0)
nb_class0 = len(set(y0))
#xxx=[None]*nb_class0
#xxx
#print(nb_class0)
#print(nb_class0) #看有多少列是发生购买的。
id_Train0 = np.array([None]*nb_class0)
#print(id_Train0)
id_Test0 = np.array([None]*nb_class0)
print(id_Test0)
for i in range(nb_class0):
    id_i0 = np.where(y0==i)[0]
    print(id_i0)
    id_i_train0, id_i_test0 = train_test_split(id_i0, test_size=0.2)
    id_Train0[i] = id_i_train0
    id_Test0[i] = id_i_test0

[None None]
[    0     1     2 ... 31425 31426 31427]
[  259  1931  2470  2484  3435  3876  4124  5319  5762  5914  7070  8438
  8977  9689 11778 11782 12226 12232 13128 13892 16064 16305 16323 16422
 16717 17766 18023 18093 18397 18667 19157 19660 19813 19952 20158 20290
 20529 20574 20992 21213 22947 22980 23104 23691 23841 24118 25506 26280
 26440 27412 28682 29258 29362 29504 29715 30219 30705]


In [13]:
#ttt = np.array([1,1,1,1,0,0,0,1,1,1,0,1,0,1])
y00 = np.array([1,2,3,0])
ttt = len(set(y00))
print(ttt)
kkk = np.array([1,2,3,4,1,0])
for i in range(ttt): #从array中最小值，即0开始记录位置。
    tti = np.where(kkk == i)[0] #把kkk中和ttt中相同的元素的位置存储在tti中。换句话说，把kkk中0或者1的位置存储下来。
    print(tti)

4
[5]
[0 4]
[1]
[2]


# In the following, we try to build a baseline model (which is not the optimal solution)

# Split data into training and testing

In [14]:
y = (y > 0)*1
nb_class = len(set(y))
print(nb_class) #看有多少列是发生购买的。
id_Train = np.array([None]*nb_class)#初始化id_Train和id_Test.
id_Test = np.array([None]*nb_class)
for i in range(nb_class):
    id_i = np.where(y==i)[0]
    id_i_train, id_i_test = train_test_split(id_i, test_size=0.3, random_state=123,shuffle=True)
    id_Train[i] = id_i_train
    id_Test[i] = id_i_test

id_Train = np.concatenate(id_Train)
id_Test = np.concatenate(id_Test)

X_train = X[id_Train]
Y_train = y[id_Train]
X_test = X[id_Test]
Y_test = y[id_Test]

2


In [15]:
X_train[0]

array([        12, 2517724481,  652481754, 2967512603, 1432783624,
       1342367140,  157533148,          2,  399159304,          0,
                2,          1,          0,          0,          0,
                3,          0,          0, 2379633508, 1284343215])

In [16]:
id_Train

array([17189,  2830, 28376, ..., 24118,  2470, 23841])

# Re-sampling

In [17]:
id_toTrain = np.array([np.where(Y_train==i)[0] for i in range(nb_class)])

size_max = [len(id_toTrain[i]) for i in range(nb_class)]
print("before resampling")
print(size_max)

blc = 150
for i in range(len(size_max)):
    if size_max[i] > blc:
        size_max[i] = int(blc*(np.log10(size_max[i]/blc)+1))
    else:
        size_max[i] = int(blc/(np.log10(blc/size_max[i])+1))

print("after resampling")
print(size_max)
for i in range(nb_class):
    if len(id_toTrain[i]) > size_max[i]:
        id_toTrain[i], tmp = train_test_split(id_toTrain[i], test_size=1-size_max[i]/len(id_toTrain[i]))
    else:
        id_toTrain[i] = np.concatenate((id_toTrain[i], id_toTrain[i][np.random.randint(len(id_toTrain[i]), size=int(size_max[i]-len(id_toTrain[i])))]))
id_toTrain = np.concatenate(id_toTrain)
X_toTrain = X_train[id_toTrain]
Y_toTrain = Y_train[id_toTrain]

before resampling
[21959, 39]
after resampling
[474, 94]


# Train the Random Forest model.

In [34]:
import pickle
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE, ADASYN
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from sklearn import metrics
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import accuracy_score as acs
from sklearn.feature_selection import SelectFromModel
from sklearn.impute import KNNImputer

print('Training')
# evaluate each model in turn
results = []
names = []
rf = RandomForestClassifier(max_depth = 15, random_state=123,max_leaf_nodes=60)
rf = rf.fit(X_toTrain, Y_toTrain)
train_pred = rf.predict(X_train)
print(metrics.accuracy_score(Y_train,train_pred))
print(metrics.classification_report(Y_train,train_pred))


print('\n')

print('Testing')


y_pred = rf.predict(X_test)
#Evaluate predictions
print(metrics.accuracy_score(Y_test,y_pred))
print(metrics.classification_report(Y_test,y_pred))

# Get numerical feature importances
feature_list = X
importances = list(rf.feature_importances_)
# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]
# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances]

Training
0.9886807891626511
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     21959
           1       0.14      1.00      0.24        39

    accuracy                           0.99     21998
   macro avg       0.57      0.99      0.62     21998
weighted avg       1.00      0.99      0.99     21998



Testing
0.9895015906680806
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      9412
           1       0.13      0.78      0.22        18

    accuracy                           0.99      9430
   macro avg       0.56      0.88      0.61      9430
weighted avg       1.00      0.99      0.99      9430



TypeError: unsupported format string passed to numpy.ndarray.__format__

In [35]:
# Create a selector object that will use the random forest classifier to identify
# features that have an importance of more than 0.002
selector = SelectFromModel(rf, threshold=0.001)

# Train the selector
selector.fit(X_toTrain, Y_toTrain)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                                 class_weight=None,
                                                 criterion='gini', max_depth=15,
                                                 max_features='auto',
                                                 max_leaf_nodes=60,
                                                 max_samples=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=100, n_jobs=None,
                                                 oob_score=False,
                                                 ran

In [36]:
# Print the names of the most important features
my_list = []

for feature_list_index in selector.get_support(indices=True):
    #print(X.columns[feature_list_index])
    my_list.append(X[feature_list_index])

In [41]:
X_important_train = selector.transform(X_toTrain)
X_important_test = selector.transform(X_test)

# New Random Forest model.
clf_important = RandomForestClassifier(max_depth = 12, random_state=123, n_estimators = 500 ,max_leaf_nodes = 15)

# Train the new classifier.
clf_important.fit(X_important_train, Y_toTrain)
y_important_pred = clf_important.predict(X_important_train)
print('train')
print(metrics.accuracy_score(Y_toTrain,y_important_pred))

print(metrics.classification_report(Y_toTrain,y_important_pred))
print('test')
y_important_test_pred = clf_important.predict(X_important_test)
print(metrics.accuracy_score(Y_test,y_important_test_pred))
print(metrics.classification_report(Y_test,y_important_test_pred))

train
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       474
           1       1.00      1.00      1.00        94

    accuracy                           1.00       568
   macro avg       1.00      1.00      1.00       568
weighted avg       1.00      1.00      1.00       568

test
0.9944856839872747
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      9412
           1       0.23      0.78      0.35        18

    accuracy                           0.99      9430
   macro avg       0.61      0.89      0.67      9430
weighted avg       1.00      0.99      1.00      9430



# Machine learning the data and output the result to a csv file.

In [28]:
# Save the model.
Rfmodel = '/Users/ganby/文件/ESCP/ML and Python/Assignment 2 and 3/model_trained.sav'
pickle.dump(clf_important, open(Rfmodel, 'wb'))

In [29]:
# load the model.
loaded_model = pickle.load(open(Rfmodel, 'rb'))

In [30]:
dft = pd.read_csv("/Users/ganby/文件/ESCP/ML and Python/Assignment 2 and 3/test1.csv")

In [31]:
labelt = dft['label'].values
labelt

array([-1, -1, -1, ..., -1, -1, -1])

In [32]:
datat = dft.drop(columns=['label','id','visitTime','purchaseTime','C1','C3','C10','C11']).values
datat

array([[         0,  403381353,  652481754, ...,          0,          0,
        4220791646],
       [         0, 1235983246,  652481754, ...,          0,          0,
        1284343215],
       [         0, 1235983246,  652481754, ...,          0,          0,
        1213938795],
       ...,
       [        23,  403381353,  652481754, ...,          0,          0,
        4220791646],
       [        23, 2541203883, 2308170622, ...,          0,          0,
        4220791646],
       [        23,  403381353,  652481754, ...,          0,          0,
        4220791646]])

In [33]:
dft['prob0'] = loaded_model.predict_proba(datat)[0:,0]
dft = dft[['id','prob0']]
dft.to_csv('/Users/ganby/文件/ESCP/ML and Python/Assignment 2 and 3/Output_result.csv')